const DEFAULT_BODY_LIMIT=16*1024;
function parseJsonBody(req,limit=DEFAULT_BODY_LIMIT){if(req.body===undefined||req.body===null)return failure('INVALID_BODY','Send a valid JSON request body.',400);let body=req.body;if(typeof body==='string'){if(Buffer.byteLength(body,'utf8')>limit)return failure('REQUEST_TOO_LARGE','The request body is too large.',413);try{body=JSON.parse(body);}catch{return failure('INVALID_JSON','Send valid JSON.',400);}}if(!body||typeof body!=='object'||Array.isArray(body))return failure('INVALID_BODY','Send a JSON object.',400);let serialized;try{serialized=JSON.stringify(body);}catch{return failure('INVALID_BODY','Send a serializable JSON object.',400);}if(Buffer.byteLength(serialized,'utf8')>limit)return failure('REQUEST_TOO_LARGE','The request body is too large.',413);return{ok:true,value:body};}
function requireMethod(req,method='POST'){return req.method===method?{ok:true}:failure('METHOD_NOT_ALLOWED',`Use ${method} for this endpoint.`,405);}
async function fetchWithTimeout(url,options={},timeoutMs=20000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal});}finally{clearTimeout(timer);}}
function sendError(res,error){const status=Number(error.status)||500;return res.status(status).json({error:{code:error.code||'PROVIDER_FAILED',message:error.publicMessage||'The provider request failed. Please try again.'}});}
function providerError(code,publicMessage,status=502){const error=new Error(publicMessage);error.code=code;error.publicMessage=publicMessage;error.status=status;return error;}
function normalizeProviderError(provider,status,payload={}){if(status===429)return providerError(`${provider}_RATE_LIMITED`,'The provider rate limit was reached. Please try again later.',429);if(status===401||status===403)return providerError(`${provider}_AUTH_FAILED`,'The secure provider configuration was rejected. Please contact the site administrator.',503);if(status>=500)return providerError(`${provider}_UNAVAILABLE`,'The provider is temporarily unavailable. Please try again.',502);const message=typeof payload.error?.message==='string'&&payload.error.message.length<240?payload.error.message:'The provider rejected the request.';return providerError(`${provider}_REJECTED`,message,400);}
function safeLog(event,metadata={}){const allowed={event:String(event).slice(0,80)};for(const key of['provider','code','status','purpose'])if(metadata[key]!==undefined)allowed[key]=metadata[key];console.error('[provider-runtime]',allowed);}
function createMemoryRateLimit({windowMs=60000,max=20}={}){const buckets=new Map();return(req)=>{const now=Date.now();const ip=String(req.headers?.['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim();for(const[key,bucket]of buckets)if(now-bucket.startedAt>windowMs)buckets.delete(key);const bucket=buckets.get(ip);if(!bucket||now-bucket.startedAt>windowMs){buckets.set(ip,{startedAt:now,count:1});return{ok:true};}bucket.count+=1;return bucket.count<=max?{ok:true}:failure('RATE_LIMITED','Too many requests. Please wait and try again.',429);};}
function failure(code,message,status){return{ok:false,error:{code,publicMessage:message,status}};}
module.exports={createMemoryRateLimit,fetchWithTimeout,normalizeProviderError,parseJsonBody,providerError,requireMethod,safeLog,sendError};
