const test=require('node:test');const assert=require('node:assert/strict');
const {dedupeBusinesses,validateRequestBody}=require('../api/local-businesses/core');
const {normaliseGooglePlace}=require('../api/local-businesses/providers/google');
const {haversine,normaliseOsmElement,withinRadius,_cache}=require('../api/local-businesses/providers/open-data');
const {discoverBusinesses}=require('../api/local-businesses/providers');
const searchHandler=require('../api/local-businesses/search');

test('normalises Google into the provider-independent model',()=>{assert.deepEqual(normaliseGooglePlace({id:'g1',displayName:{text:'Alpha'},primaryType:'dental_clinic',types:['health'],rating:4.7,userRatingCount:82,formattedAddress:'Road',nationalPhoneNumber:'040',internationalPhoneNumber:'+9140',websiteUri:'https://example.com',businessStatus:'OPERATIONAL',googleMapsUri:'https://maps.google.com/x',location:{latitude:17.4,longitude:78.5}}),{id:'g1',name:'Alpha',category:'Dental Clinic',types:['health'],rating:4.7,reviewCount:82,address:'Road',phone:'040',internationalPhone:'+9140',website:'https://example.com',websiteStatus:'not_checked',businessStatus:'OPERATIONAL',source:'google',sourceUrl:'https://maps.google.com/x',latitude:17.4,longitude:78.5,openingHours:'',tags:{}});});
test('normalises OpenStreetMap without inventing ratings or status',()=>{const item=normaliseOsmElement({type:'node',id:9,lat:17.4,lon:78.5,tags:{name:'Beta Cafe',amenity:'cafe','addr:street':'Main Road',phone:'+91123',website:'https://beta.test',opening_hours:'Mo-Sa 09:00-18:00'}});assert.equal(item.source,'openstreetmap');assert.equal(item.rating,null);assert.equal(item.reviewCount,null);assert.equal(item.businessStatus,'');assert.equal(item.sourceUrl,'https://www.openstreetmap.org/node/9');assert.equal(item.openingHours,'Mo-Sa 09:00-18:00');});
test('missing fields remain empty or null',()=>{const google=normaliseGooglePlace({id:'g2'});const osm=normaliseOsmElement({type:'node',id:10,tags:{name:'Unknown'}});assert.equal(google.reviewCount,null);assert.equal(google.latitude,null);assert.equal(osm.phone,'');assert.equal(osm.website,'');assert.equal(osm.latitude,null);});
test('validates provider selection and radius',()=>{assert.equal(validateRequestBody({location:'Hyderabad',radiusKm:5,provider:'auto'}).ok,true);assert.equal(validateRequestBody({location:'Hyderabad',radiusKm:3}).error.code,'INVALID_RADIUS');assert.equal(validateRequestBody({location:'Hyderabad',radiusKm:5,provider:'other'}).error.code,'INVALID_PROVIDER');});
test('selects Google when requested',async()=>{const old=global.fetch;global.fetch=async()=>({ok:true,status:200,json:async()=>({places:[{id:'g3',displayName:{text:'Google Result'}}]})});const result=await discoverBusinesses({provider:'google',location:'Hyderabad',category:'',radiusKm:5,pageToken:''},{googleApiKey:'key'});assert.equal(result.provider,'google');global.fetch=old;});
test('Auto falls back to Open Data when Google is unavailable',async()=>{_cache.clear();const old=global.fetch;global.fetch=async(url)=>String(url).includes('nominatim')?response([{lat:'17.4',lon:'78.5',display_name:'Hyderabad'}]):response({elements:[{type:'node',id:11,lat:17.401,lon:78.501,tags:{name:'Fallback Shop',shop:'general'}}]});const result=await discoverBusinesses({provider:'auto',location:'Auto Fallback Unique',category:'',radiusKm:2,pageToken:''},{googleApiKey:''});assert.equal(result.provider,'open_data');assert.equal(result.fallback.code,'GOOGLE_NOT_CONFIGURED');assert.equal(result.businesses[0].name,'Fallback Shop');global.fetch=old;});
test('deduplicates businesses',()=>{assert.deepEqual(dedupeBusinesses([{id:'a'},{id:'a'},{id:'b'}]).map((v)=>v.id),['a','b']);});
test('radius filtering uses actual coordinates',()=>{const center={latitude:17.4,longitude:78.5};assert.ok(haversine(17.4,78.5,17.401,78.501)<200);assert.equal(withinRadius({latitude:17.401,longitude:78.501},center,200),true);assert.equal(withinRadius({latitude:18,longitude:79},center,200),false);});
test('nullable ratings survive rating filters with clear provider UI handling',async()=>{const {filterBusinesses}=await import('../assets/js/local-business/business-filters.mjs');const businesses=[{id:'osm',name:'OSM',website:'',rating:null,reviewCount:null,phone:'',source:'openstreetmap',category:'Cafe',businessStatus:''},{id:'google',name:'Google',website:'',rating:3,reviewCount:5,phone:'',source:'google',category:'Cafe',businessStatus:''}];const filtered=filterBusinesses(businesses,{website:'all',rating:4,reviews:20,phone:false,source:'',category:'',businessStatus:'',sort:'rating'});assert.deepEqual(filtered.map((v)=>v.id),['osm']);});
test('provider errors remain provider-specific',async()=>{const old=global.fetch;global.fetch=async()=>({ok:false,status:429,json:async()=>({error:{status:'RESOURCE_EXHAUSTED',message:'Quota reached'}})});await assert.rejects(()=>discoverBusinesses({provider:'google',location:'X',category:'',radiusKm:5,pageToken:''},{googleApiKey:'key'}),(error)=>error.code==='GOOGLE_QUOTA_EXCEEDED');global.fetch=old;});
test('endpoint works without GOOGLE_PLACES_API_KEY in Auto mode',async()=>{_cache.clear();const oldFetch=global.fetch;const oldKey=process.env.GOOGLE_PLACES_API_KEY;delete process.env.GOOGLE_PLACES_API_KEY;global.fetch=async(url)=>String(url).includes('nominatim')?response([{lat:'17.4',lon:'78.5'}]):response({elements:[{type:'node',id:12,lat:17.4,lon:78.5,tags:{name:'Free Result',amenity:'clinic'}}]});const res=mockResponse();await searchHandler({method:'POST',body:{location:'No Key Unique',category:'',radiusKm:2,provider:'auto'},headers:{'content-type':'application/json','x-forwarded-for':'no-key-auto'},socket:{}},res);assert.equal(res.statusCode,200);assert.equal(res.body.provider,'open_data');global.fetch=oldFetch;if(oldKey)process.env.GOOGLE_PLACES_API_KEY=oldKey;});
function response(data,status=200){return{ok:status>=200&&status<300,status,json:async()=>data};}function mockResponse(){return{statusCode:200,body:null,headers:{},setHeader(k,v){this.headers[k]=v;},status(code){this.statusCode=code;return this;},json(body){this.body=body;return this;}};}
