const test=require('node:test');const assert=require('node:assert/strict');const{dedupeBusinesses,validateRequestBody}=require('../api/local-businesses/core');const{normaliseGooglePlace}=require('../api/local-businesses/providers/google');const{haversine,normaliseOsmElement,withinRadius,_cache}=require('../api/local-businesses/providers/open-data');const{discoverBusinesses}=require('../api/local-businesses/providers');const searchHandler=require('../api/local-businesses/search');
test('normalises Google into the canonical model',()=>{const item=normaliseGooglePlace({id:'g1',displayName:{text:'Alpha'},primaryType:'dental_clinic',types:['health'],rating:4.7,userRatingCount:82,formattedAddress:'Road',internationalPhoneNumber:'+9140',websiteUri:'https://example.com',businessStatus:'OPERATIONAL',googleMapsUri:'https://maps.google.com/x',location:{latitude:17.4,longitude:78.5}});assert.equal(item.provider,'google');assert.equal(item.providerId,'g1');assert.equal(item.phone,'+9140');assert.equal(item.reviewCount,82);assert.ok(item.createdAt);});
test('normalises OpenStreetMap without inventing ratings or status',()=>{const item=normaliseOsmElement({type:'node',id:9,lat:17.4,lon:78.5,tags:{name:'Beta Cafe',amenity:'cafe','addr:street':'Main Road',phone:'+91123',website:'https://beta.test',opening_hours:'Mo-Sa 09:00-18:00'}});assert.equal(item.provider,'openstreetmap');assert.equal(item.providerId,'node:9');assert.equal(item.rating,null);assert.equal(item.reviewCount,null);assert.equal(item.businessStatus,'');assert.equal(item.openingHours,'Mo-Sa 09:00-18:00');});
test('missing fields remain empty or null',()=>{const google=normaliseGooglePlace({id:'g2',displayName:{text:'Unknown'}});const osm=normaliseOsmElement({type:'node',id:10,tags:{name:'Unknown'}});assert.equal(google.reviewCount,null);assert.equal(osm.phone,'');assert.equal(osm.latitude,null);});
test('validates provider selection and radius',()=>{assert.equal(validateRequestBody({location:'Hyderabad',radiusKm:5,provider:'auto'}).ok,true);assert.equal(validateRequestBody({location:'Hyderabad',radiusKm:3}).error.code,'INVALID_RADIUS');assert.equal(validateRequestBody({location:'Hyderabad',radiusKm:5,provider:'other'}).error.code,'INVALID_PROVIDER');});
test('selects Google when requested',async()=>{const old=global.fetch;global.fetch=async()=>response({places:[{id:'g3',displayName:{text:'Google Result'}}]});try{const result=await discoverBusinesses({provider:'google',location:'Hyderabad',category:'',radiusKm:5,pageToken:''},{googleApiKey:'key'});assert.equal(result.provider,'google');}finally{global.fetch=old;}});
test('Auto falls back to Open Data when Google is unavailable',async()=>{_cache.clear();const old=global.fetch;global.fetch=async url=>String(url).includes('nominatim')?response([{lat:'17.4',lon:'78.5',display_name:'Hyderabad'}]):response({elements:[{type:'node',id:11,lat:17.401,lon:78.501,tags:{name:'Fallback Shop',shop:'general'}}]});try{const result=await discoverBusinesses({provider:'auto',location:'Auto Fallback Unique',category:'',radiusKm:2,pageToken:''},{googleApiKey:''});assert.equal(result.provider,'open_data');assert.equal(result.businesses[0].name,'Fallback Shop');}finally{global.fetch=old;}});
test('deduplicates canonical businesses',()=>{assert.deepEqual(dedupeBusinesses([{provider:'google',providerId:'a'},{provider:'google',providerId:'a'},{provider:'google',providerId:'b'}]).map(v=>v.providerId),['a','b']);});
test('radius filtering uses coordinates',()=>{const center={latitude:17.4,longitude:78.5};assert.ok(haversine(17.4,78.5,17.401,78.501)<200);assert.equal(withinRadius({latitude:17.401,longitude:78.501},center,200),true);});
test('nullable ratings are safe',async()=>{const{filterBusinesses}=await import('../assets/js/local-business/business-filters.mjs');const businesses=[{provider:'openstreetmap',providerId:'1',name:'OSM',website:'',rating:null,reviewCount:null,phone:'',category:'Cafe',businessStatus:''}];assert.equal(filterBusinesses(businesses,{website:'all',rating:0,reviews:0,phone:false,source:'',category:'',businessStatus:'',sort:'rating'}).length,1);});
test('rendering escapes provider values and unsafe URLs',async()=>{const{renderBusinessCard}=await import('../assets/js/local-business/business-renderer.mjs');const html=renderBusinessCard({provider:'openstreetmap',providerId:'node:1',name:'<img src=x onerror=alert(1)>',category:'Cafe',rating:null,reviewCount:null,address:'<script>x</script>',phone:'',website:'javascript:alert(1)',businessStatus:'',sourceUrl:'https://openstreetmap.org/node/1'});assert.equal(html.includes('<img src=x'),false);assert.equal(html.includes('<script>'),false);assert.equal(html.includes('javascript:alert'),false);assert.match(html,/Rating unavailable from Open Data/);assert.equal(html.includes('Not available · Not available'),false);});
test('oversized bodies are rejected',()=>assert.equal(validateRequestBody({location:'x',category:'a'.repeat(5000),radiusKm:5,provider:'auto'}).error.code,'REQUEST_TOO_LARGE'));
test('endpoint works without Google key and without configured persistence',async()=>{_cache.clear();const oldFetch=global.fetch,oldKey=process.env.GOOGLE_PLACES_API_KEY;delete process.env.GOOGLE_PLACES_API_KEY;global.fetch=async url=>String(url).includes('nominatim')?response([{lat:'17.4',lon:'78.5'}]):response({elements:[{type:'node',id:12,lat:17.4,lon:78.5,tags:{name:'Free Result',amenity:'clinic'}}]});try{const out=mockResponse();await searchHandler({method:'POST',body:{location:'No Key Unique',category:'',radiusKm:2,provider:'auto'},headers:{'content-type':'application/json','x-forwarded-for':'no-key-auto'},socket:{}},out);assert.equal(out.statusCode,200);assert.equal(out.body.provider,'open_data');}finally{global.fetch=oldFetch;if(oldKey)process.env.GOOGLE_PLACES_API_KEY=oldKey;}});
function response(data,status=200){return{ok:status>=200&&status<300,status,json:async()=>data};}function mockResponse(){return{statusCode:200,body:null,headers:{},setHeader(k,v){this.headers[k]=v;},status(code){this.statusCode=code;return this;},json(body){this.body=body;return this;}};}
