const test=require('node:test');const assert=require('node:assert/strict');const handler=require('../api/persistence');const repo=require('../api/persistence/repository');const{normalizeBusiness}=require('../api/local-businesses/business-model');
const WORKSPACE='123e4567-e89b-42d3-a456-426614174000';
function res(){return{statusCode:0,body:null,headers:{},setHeader(k,v){this.headers[k]=v;},status(code){this.statusCode=code;return this;},json(body){this.body=body;return this;}};}function req(method,resource,body,id=''){return{method,body,query:{resource,id},headers:{'x-workspace-id':WORKSPACE}};}function response(data,status=200){return{ok:status>=200&&status<300,status,json:async()=>data};}function configure(){process.env.SUPABASE_URL='https://database.example';process.env.SUPABASE_SERVICE_ROLE_KEY='sb_secret_server-only';}
test('canonical model is shared and rejects invalid providers',()=>{const item=normalizeBusiness({provider:'google',providerId:'g1',name:'Alpha',rating:4.2,reviewCount:12,website:'https://example.com'});assert.equal(item.providerId,'g1');assert.equal(item.city,'');assert.equal(item.rating,4.2);assert.equal(normalizeBusiness({provider:'unknown',providerId:'1',name:'X'}),null);});
test('persistence endpoint validates workspace and body size',async()=>{let out=res();await handler({method:'GET',query:{resource:'saved_leads'},headers:{}},out);assert.equal(out.statusCode,400);out=res();await handler(req('POST','saved_leads','x'.repeat(17000)),out);assert.equal(out.statusCode,413);});
test('saving a lead supports new secret keys without treating them as JWTs',async()=>{configure();const old=global.fetch,calls=[];global.fetch=async(url,options)=>{calls.push({url,options});if(url.includes('/businesses?'))return response([{id:'business-1'}]);if(url.includes('/saved_leads'))return response([{id:'lead-1'}]);return response([{id:'activity-1'}]);};try{const out=res();await handler(req('POST','saved_leads',{business:{provider:'google',providerId:'g1',name:'Alpha'}}),out);assert.equal(out.statusCode,201);assert.equal(out.body.item.id,'lead-1');assert.equal(calls.length,3);assert.equal(calls[0].options.headers.apikey,'sb_secret_server-only');assert.equal(calls[0].options.headers.Authorization,undefined);assert.doesNotMatch(JSON.stringify(out.body),/sb_secret_server-only/);}finally{global.fetch=old;}});
test('duplicate saves return a stable conflict',async()=>{configure();const old=global.fetch;let count=0;global.fetch=async()=>++count===1?response([{id:'business-1'}]):response({message:'duplicate'},409);try{const out=res();await handler(req('POST','saved_leads',{business:{provider:'google',providerId:'g1',name:'Alpha'}}),out);assert.equal(out.statusCode,409);assert.equal(out.body.error.code,'DUPLICATE_RECORD');}finally{global.fetch=old;}});
test('search history records canonical criteria',async()=>{configure();const old=global.fetch;let body;global.fetch=async(_url,options)=>{body=JSON.parse(options.body);return response([{id:'history-1'}]);};try{await repo.recordSearch(WORKSPACE,{location:'Hyderabad',category:'Cafe',radiusKm:5,provider:'auto'},{provider:'open_data',businesses:[{}]});assert.equal(body.result_count,1);assert.equal(body.provider,'open_data');}finally{global.fetch=old;}});
test('notes support create update and delete',async()=>{configure();const old=global.fetch,calls=[];global.fetch=async(url,options)=>{calls.push({url,options});return options.method==='DELETE'?{ok:true,status:204,json:async()=>null}:response([{id:'note-1',content:'Follow up'}]);};try{let out=res();await handler(req('POST','lead_notes',{savedLeadId:'lead-1',content:'Follow up'}),out);assert.equal(out.statusCode,201);out=res();await handler(req('PATCH','lead_notes',{content:'Updated'},'note-1'),out);assert.equal(out.statusCode,200);out=res();await handler(req('DELETE','lead_notes',undefined,'note-1'),out);assert.equal(out.statusCode,200);assert.ok(calls.some(call=>call.options.method==='PATCH'));assert.ok(calls.some(call=>call.options.method==='DELETE'));}finally{global.fetch=old;}});
test('activity validation rejects unsupported events',async()=>{configure();const out=res();await handler(req('POST','activity_log',{eventType:'secret_event'}),out);assert.equal(out.statusCode,400);assert.equal(out.body.error.code,'INVALID_ACTIVITY');});
