const test=require('node:test');
const assert=require('node:assert/strict');
const runtime=require('../api/_shared/provider-runtime');
const handler=require('../api/legacy/anthropic/messages');
const ui=require('../assets/js/security/safe-ui');

function response(){return{statusCode:0,headers:{},payload:null,setHeader(k,v){this.headers[k]=v;},status(code){this.statusCode=code;return this;},json(value){this.payload=value;return this;}};}
function request(body,method='POST',ip=Math.random().toString()){return{method,body,headers:{'x-forwarded-for':ip}};}
function withEnv(value,fn){const old=process.env.ANTHROPIC_API_KEY;if(value===undefined)delete process.env.ANTHROPIC_API_KEY;else process.env.ANTHROPIC_API_KEY=value;return Promise.resolve(fn()).finally(()=>{if(old===undefined)delete process.env.ANTHROPIC_API_KEY;else process.env.ANTHROPIC_API_KEY=old;});}

test('rejects unsupported methods',async()=>{const res=response();await handler(request({},'GET'),res);assert.equal(res.statusCode,405);assert.equal(res.headers.Allow,'POST');});
test('rejects invalid JSON and oversized bodies',async()=>{let res=response();await handler(request('{'),res);assert.equal(res.statusCode,400);assert.equal(res.payload.error.code,'INVALID_JSON');res=response();await handler(request('x'.repeat(13*1024)),res);assert.equal(res.statusCode,413);});
test('missing server configuration is structured and does not echo browser data',()=>withEnv(undefined,async()=>{const res=response();await handler(request({purpose:'lead_queries',prompt:'secret-from-browser'}),res);assert.equal(res.statusCode,503);assert.equal(res.payload.error.code,'LEGACY_PROVIDER_NOT_CONFIGURED');assert.doesNotMatch(JSON.stringify(res.payload),/secret-from-browser/);}));
test('migrated provider success returns text but never the server secret',()=>withEnv('server-only-secret',async()=>{const old=global.fetch;let sent;global.fetch=async(_url,options)=>{sent=options;return{ok:true,status:200,json:async()=>({content:[{text:'safe result'}]})};};try{const res=response();await handler(request({purpose:'lead_queries',prompt:'find leads'}),res);assert.equal(res.statusCode,200);assert.deepEqual(res.payload,{text:'safe result'});assert.equal(sent.headers['x-api-key'],'server-only-secret');assert.doesNotMatch(JSON.stringify(res.payload),/server-only-secret/);}finally{global.fetch=old;}}));
test('provider failures are normalized and secrets are never logged',()=>withEnv('never-log-this',async()=>{const oldFetch=global.fetch,oldError=console.error;const logs=[];global.fetch=async()=>({ok:false,status:403,json:async()=>({error:{message:'permission denied'}})});console.error=(...args)=>logs.push(args);try{const res=response();await handler(request({purpose:'lead_outreach',prompt:'hello'}),res);assert.equal(res.statusCode,503);assert.equal(res.payload.error.code,'ANTHROPIC_AUTH_FAILED');assert.doesNotMatch(JSON.stringify(logs),/never-log-this|hello/);}finally{global.fetch=oldFetch;console.error=oldError;}}));
test('provider timeout aborts the request',async()=>{const old=global.fetch;global.fetch=(_url,{signal})=>new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'}))));try{await assert.rejects(runtime.fetchWithTimeout('https://example.test',{},5),{name:'AbortError'});}finally{global.fetch=old;}});
test('safe UI rejects injection URLs and unsafe contact values',()=>{assert.equal(ui.escapeHtml('<img src=x onerror=alert(1)>'),'&lt;img src=x onerror=alert(1)&gt;');assert.equal(ui.safeUrl('javascript:alert(1)'),'');assert.equal(ui.safePhone('123<script>'),'');assert.equal(ui.whatsAppUrl('not-a-phone'),'');});
test('safe attributes and external links enforce protections',()=>{const attrs={};const el={setAttribute(k,v){attrs[k]=v;}};assert.equal(ui.setSafeAttribute(el,'onclick','alert(1)'),false);assert.equal(ui.setSafeAttribute(el,'title','safe'),true);assert.equal(attrs.title,'safe');const link={};assert.equal(ui.secureExternalLink(link,'https://example.com/path'),true);assert.equal(link.rel,'noopener noreferrer');assert.equal(link.target,'_blank');});
test('provider failures never expose raw upstream secrets',()=>{const error=runtime.normalizeProviderError('PAID_API',403,{error:{message:'key abc123 rejected'}});const res=response();runtime.sendError(res,error);assert.equal(res.payload.error.code,'PAID_API_AUTH_FAILED');assert.doesNotMatch(JSON.stringify(res.payload),/abc123/);});
