const db=require('./supabase');const{normalizeBusiness}=require('../local-businesses/business-model');
async function list(resource,workspaceId){const table=tableFor(resource);const select=resource==='saved_leads'?'*,businesses(*),lead_notes(*)':'*';return db.query(table,{query:`workspace_id=eq.${workspaceId}&select=${select}&order=created_at.desc&limit=100`});}
async function saveLead(workspaceId,input){const business=normalizeBusiness(input);if(!business)throw invalid('INVALID_BUSINESS','Choose a valid business to save.');const row=toBusinessRow(business);const saved=await db.query('businesses',{method:'POST',query:'on_conflict=provider,provider_id',body:row,prefer:'resolution=merge-duplicates,return=representation'});const businessId=saved?.[0]?.id;if(!businessId)throw db.error('PERSISTENCE_FAILED','The business could not be saved.',502);const lead=await db.query('saved_leads',{method:'POST',body:{workspace_id:workspaceId,business_id:businessId}});await activity(workspaceId,'saved_business',businessId,{provider:business.provider});return lead?.[0]||null;}
async function removeLead(workspaceId,id){await ownedDelete('saved_leads',workspaceId,id);return{deleted:true};}
async function recordSearch(workspaceId,criteria,result){if(!workspaceId)return null;return db.query('search_history',{method:'POST',body:{workspace_id:workspaceId,location:criteria.location,category:criteria.category||'',radius_km:criteria.radiusKm,provider:result.provider||criteria.provider,result_count:Array.isArray(result.businesses)?result.businesses.length:0}});}
async function saveSearch(workspaceId,input){validateCriteria(input);return db.query('saved_searches',{method:'POST',body:{workspace_id:workspaceId,name:limited(input.name,80,'Search'),location:limited(input.location,120),category:limited(input.category,80),radius_km:Number(input.radiusKm),provider:input.provider}});}
async function createNote(workspaceId,input){const content=note(input.content);const lead=limited(input.savedLeadId,64);return db.query('lead_notes',{method:'POST',body:{workspace_id:workspaceId,saved_lead_id:lead,content}});}
async function updateNote(workspaceId,id,input){return db.query('lead_notes',{method:'PATCH',query:`workspace_id=eq.${workspaceId}&id=eq.${id}`,body:{content:note(input.content),updated_at:new Date().toISOString()}});}
async function ownedDelete(table,workspaceId,id){tableFor(table);await db.query(table,{method:'DELETE',query:`workspace_id=eq.${workspaceId}&id=eq.${id}`,prefer:'return=minimal'});return{deleted:true};}
async function activity(workspaceId,eventType,businessId=null,metadata={}){const allowed=new Set(['viewed_business','saved_business','updated_note','reran_search','website_demo_generated']);if(!allowed.has(eventType))throw invalid('INVALID_ACTIVITY','Choose a supported activity.');return db.query('activity_log',{method:'POST',body:{workspace_id:workspaceId,event_type:eventType,business_id:businessId||null,metadata:isObject(metadata)?metadata:{}}});}
async function saveWebsitePreview(workspaceId,input){if(!isObject(input))throw invalid('INVALID_PREVIEW','Generate a valid website preview.');const shareToken=limited(input.shareToken,36);if(!UUID.test(shareToken))throw invalid('INVALID_PREVIEW_TOKEN','Generate a valid preview link.');const business=normalizeBusiness(input.business);if(!business)throw invalid('INVALID_BUSINESS','Choose a valid business for the preview.');const preview=sanitizePreview(input.preview);const metadata={shareToken,preview,businessRef:{provider:business.provider,providerId:business.providerId}};const result=await db.query('activity_log',{method:'POST',body:{workspace_id:workspaceId,event_type:'website_demo_generated',business_id:null,metadata}});return{shareToken,createdAt:result?.[0]?.created_at||new Date().toISOString()};}
async function publicPreview(shareToken){if(!UUID.test(String(shareToken||'')))throw invalid('INVALID_PREVIEW_TOKEN','This preview link is invalid.');const token=encodeURIComponent(shareToken);const rows=await db.query('activity_log',{query:`event_type=eq.website_demo_generated&metadata->>shareToken=eq.${token}&select=metadata,created_at&order=created_at.desc&limit=1`});const row=rows?.[0];const preview=row?.metadata?.preview;if(!preview)return null;return{preview:sanitizePreview(preview),createdAt:row.created_at||''};}
function tableFor(resource){const allowed=new Set(['saved_leads','search_history','saved_searches','lead_notes','activity_log']);if(!allowed.has(resource))throw invalid('INVALID_RESOURCE','Choose a supported persistence resource.');return resource;}
function validateCriteria(input){if(!isObject(input)||!limited(input.location,120)||![2,5,10,20].includes(Number(input.radiusKm))||!['auto','google','open_data'].includes(input.provider))throw invalid('INVALID_SEARCH','Enter a valid saved search.');}
function toBusinessRow(b){return{provider:b.provider,provider_id:b.providerId,name:b.name,category:b.category,address:b.address,city:b.city,state:b.state,country:b.country,latitude:b.latitude,longitude:b.longitude,phone:b.phone,email:b.email,website:b.website,rating:b.rating,review_count:b.reviewCount,business_status:b.businessStatus,source_url:b.sourceUrl,updated_at:new Date().toISOString()};}
function sanitizePreview(input){if(!isObject(input))throw invalid('INVALID_PREVIEW','Generate a valid website preview.');const business=isObject(input.business)?input.business:{};const hero=isObject(input.hero)?input.hero:{};const contact=isObject(input.contact)?input.contact:{};const story=isObject(input.story)?input.story:{};const allowedThemes=new Set(['care','hospitality','service','professional','wellness','education','retail','modern']);const score=(value)=>{const n=Number(value);return Number.isFinite(n)?Math.min(100,Math.max(0,Math.round(n))):null;};const publicBusiness={name:limited(business.name,100),category:limited(business.category,80),address:limited(business.address,180),location:limited(business.location,100),phone:limited(business.phone,40),email:limited(business.email,120),website:httpUrl(business.website),rating:business.rating!==null&&business.rating!==undefined&&business.rating!==''&&Number.isFinite(Number(business.rating))?Number(business.rating):null,reviewCount:business.reviewCount!==null&&business.reviewCount!==undefined&&business.reviewCount!==''&&Number.isFinite(Number(business.reviewCount))?Math.max(0,Math.trunc(Number(business.reviewCount))):null};const services=Array.isArray(input.services)?input.services.slice(0,6).map(item=>({title:limited(item?.title,80),description:limited(item?.description,240)})).filter(item=>item.title):[];const proof=Array.isArray(input.proof)?input.proof.slice(0,4).map(item=>({value:limited(item?.value,40),label:limited(item?.label,100)})).filter(item=>item.value):[];const reasons=Array.isArray(input.auditContext?.reasons)?input.auditContext.reasons.slice(0,4).map(item=>limited(item,120)).filter(Boolean):[];return{version:1,theme:allowedThemes.has(input.theme)?input.theme:'modern',business:publicBusiness,hero:{eyebrow:limited(hero.eyebrow,80),title:limited(hero.title,100)||publicBusiness.name,subtitle:limited(hero.subtitle,260),primaryCta:limited(hero.primaryCta,40),secondaryCta:limited(hero.secondaryCta,40)},proof,services,story:{title:limited(story.title,140),body:limited(story.body,500)},contact:{title:limited(contact.title,80),phone:limited(contact.phone,40),email:limited(contact.email,120),address:limited(contact.address,180),location:limited(contact.location,100)},auditContext:isObject(input.auditContext)?{healthScore:score(input.auditContext.healthScore),opportunityScore:score(input.auditContext.opportunityScore),reasons}:null,disclaimer:limited(input.disclaimer,300),generatedAt:limited(input.generatedAt,40)};}
function httpUrl(value){try{const url=new URL(typeof value==='string'?value:'');return['http:','https:'].includes(url.protocol)?url.href:'';}catch{return'';}}
function note(value){const result=limited(value,2000);if(!result)throw invalid('INVALID_NOTE','Enter a note.');return result;}function limited(value,max,fallback=''){return typeof value==='string'?value.trim().slice(0,max):fallback;}function isObject(value){return value&&typeof value==='object'&&!Array.isArray(value);}function invalid(code,message){return Object.assign(new Error(message),{code,status:400});}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
module.exports={activity,createNote,list,ownedDelete,publicPreview,recordSearch,removeLead,saveLead,saveSearch,saveWebsitePreview,sanitizePreview,updateNote};
