const db=require('./supabase');const{normalizeBusiness}=require('../local-businesses/business-model');
async function list(resource,workspaceId){const table=tableFor(resource);const select=resource==='saved_leads'?'*,businesses(*),lead_notes(*)':'*';return db.query(table,{query:`workspace_id=eq.${workspaceId}&select=${select}&order=created_at.desc&limit=100`});}
async function saveLead(workspaceId,input){const business=normalizeBusiness(input);if(!business)throw invalid('INVALID_BUSINESS','Choose a valid business to save.');const row=toBusinessRow(business);const saved=await db.query('businesses',{method:'POST',query:'on_conflict=provider,provider_id',body:row,prefer:'resolution=merge-duplicates,return=representation'});const businessId=saved?.[0]?.id;if(!businessId)throw db.error('PERSISTENCE_FAILED','The business could not be saved.',502);const lead=await db.query('saved_leads',{method:'POST',body:{workspace_id:workspaceId,business_id:businessId}});await activity(workspaceId,'saved_business',businessId,{provider:business.provider});return lead?.[0]||null;}
async function removeLead(workspaceId,id){await ownedDelete('saved_leads',workspaceId,id);return{deleted:true};}
async function recordSearch(workspaceId,criteria,result){if(!workspaceId)return null;return db.query('search_history',{method:'POST',body:{workspace_id:workspaceId,location:criteria.location,category:criteria.category||'',radius_km:criteria.radiusKm,provider:result.provider||criteria.provider,result_count:Array.isArray(result.businesses)?result.businesses.length:0}});}
async function saveSearch(workspaceId,input){validateCriteria(input);return db.query('saved_searches',{method:'POST',body:{workspace_id:workspaceId,name:limited(input.name,80,'Search'),location:limited(input.location,120),category:limited(input.category,80),radius_km:Number(input.radiusKm),provider:input.provider}});}
async function createNote(workspaceId,input){const content=note(input.content);const lead=limited(input.savedLeadId,64);return db.query('lead_notes',{method:'POST',body:{workspace_id:workspaceId,saved_lead_id:lead,content}});}
async function updateNote(workspaceId,id,input){return db.query('lead_notes',{method:'PATCH',query:`workspace_id=eq.${workspaceId}&id=eq.${id}`,body:{content:note(input.content),updated_at:new Date().toISOString()}});}
async function ownedDelete(table,workspaceId,id){tableFor(table);await db.query(table,{method:'DELETE',query:`workspace_id=eq.${workspaceId}&id=eq.${id}`,prefer:'return=minimal'});return{deleted:true};}
async function activity(workspaceId,eventType,businessId=null,metadata={}){const allowed=new Set(['viewed_business','saved_business','updated_note','reran_search']);if(!allowed.has(eventType))throw invalid('INVALID_ACTIVITY','Choose a supported activity.');return db.query('activity_log',{method:'POST',body:{workspace_id:workspaceId,event_type:eventType,business_id:businessId||null,metadata:isObject(metadata)?metadata:{}}});}
function tableFor(resource){const allowed=new Set(['saved_leads','search_history','saved_searches','lead_notes','activity_log']);if(!allowed.has(resource))throw invalid('INVALID_RESOURCE','Choose a supported persistence resource.');return resource;}
function validateCriteria(input){if(!isObject(input)||!limited(input.location,120)||![2,5,10,20].includes(Number(input.radiusKm))||!['auto','google','open_data'].includes(input.provider))throw invalid('INVALID_SEARCH','Enter a valid saved search.');}
function toBusinessRow(b){return{provider:b.provider,provider_id:b.providerId,name:b.name,category:b.category,address:b.address,city:b.city,state:b.state,country:b.country,latitude:b.latitude,longitude:b.longitude,phone:b.phone,email:b.email,website:b.website,rating:b.rating,review_count:b.reviewCount,business_status:b.businessStatus,source_url:b.sourceUrl,updated_at:new Date().toISOString()};}
function note(value){const result=limited(value,2000);if(!result)throw invalid('INVALID_NOTE','Enter a note.');return result;}function limited(value,max,fallback=''){return typeof value==='string'?value.trim().slice(0,max):fallback;}function isObject(value){return value&&typeof value==='object'&&!Array.isArray(value);}function invalid(code,message){return Object.assign(new Error(message),{code,status:400});}
module.exports={activity,createNote,list,ownedDelete,recordSearch,removeLead,saveLead,saveSearch,updateNote};
