const NOMINATIM_ENDPOINT='https://nominatim.openstreetmap.org/search';
const OVERPASS_ENDPOINTS=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];
const USER_AGENT='FirstCustomer-BusinessDiscovery/1.0 (https://www.firstcustomer.in/)';
const CACHE_TTL={geocode:24*60*60*1000,search:10*60*1000};
const cache=new Map();
let nextNominatimRequestAt=0;

async function searchOpenData(criteria,options={}){
  const geocode=await geocodeLocation(criteria.location,options);
  const radiusMeters=criteria.radiusKm*1000;
  const cacheKey=`search:${geocode.latitude.toFixed(4)}:${geocode.longitude.toFixed(4)}:${radiusMeters}:${criteria.category.toLowerCase()}`;
  const cached=getCache(cacheKey); if(cached)return cached;
  const query=buildOverpassQuery(geocode.latitude,geocode.longitude,radiusMeters,criteria.category);
  const endpoints=options.overpassEndpoint?[options.overpassEndpoint]:OVERPASS_ENDPOINTS;let response;let lastError;
  for(const endpoint of endpoints){try{response=await fetchWithTimeout(endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8','User-Agent':USER_AGENT},body:`data=${encodeURIComponent(query)}`},options.overpassTimeoutMs||12000);if(response.ok)break;lastError=providerError(response.status===429?'OPEN_DATA_RATE_LIMITED':'OPEN_DATA_UNAVAILABLE',`Open Data provider returned HTTP ${response.status}.`,response.status===429?429:502);}catch(error){lastError=providerError('OPEN_DATA_TIMEOUT',error.name==='AbortError'?'Open Data search timed out. Please try again.':'Open Data search could not be reached.',504);}}
  if(!response?.ok)throw lastError||providerError('OPEN_DATA_UNAVAILABLE','Open Data search is temporarily unavailable.',502);
  const data=await response.json().catch(()=>({elements:[]}));
  const businesses=dedupe((data.elements||[]).map(normaliseOsmElement).filter((business)=>withinRadius(business,geocode,radiusMeters)&&matchesCategory(business,criteria.category))).slice(0,200);
  const result={provider:'open_data',businesses,nextPageToken:null,notice:'Open Data results do not include Google ratings or review counts, and phone or website information may be incomplete.'}; setCache(cacheKey,result,CACHE_TTL.search);return result;
}

async function geocodeLocation(location,options={}){const key=`geocode:${location.toLowerCase()}`;const cached=getCache(key);if(cached)return cached;await waitForNominatimSlot();const url=`${options.nominatimEndpoint||NOMINATIM_ENDPOINT}?format=jsonv2&limit=1&q=${encodeURIComponent(location)}`;let response;try{response=await fetchWithTimeout(url,{headers:{'User-Agent':USER_AGENT,'Accept-Language':'en'}},options.nominatimTimeoutMs||10000);}catch(error){throw providerError('LOCATION_LOOKUP_FAILED',error.name==='AbortError'?'Location lookup timed out.':'Location lookup could not be reached.',502);}if(!response.ok)throw providerError(response.status===429?'OPEN_DATA_RATE_LIMITED':'LOCATION_LOOKUP_FAILED','Location lookup is temporarily unavailable.',response.status===429?429:502);const data=await response.json().catch(()=>[]);if(!data.length)throw providerError('LOCATION_NOT_FOUND','OpenStreetMap could not find that location.',404);const result={latitude:Number(data[0].lat),longitude:Number(data[0].lon),displayName:text(data[0].display_name)};setCache(key,result,CACHE_TTL.geocode);return result;}
function buildOverpassQuery(lat,lon,radius,category=''){const keys=['amenity','shop','office','craft','tourism','leisure'];const targeted=categoryClauses(category);const clauses=targeted.length?targeted.map(([key,value])=>`nwr(around:${radius},${lat},${lon})["name"]["${key}"="${value}"];`):keys.map((key)=>`nwr(around:${radius},${lat},${lon})["name"]["${key}"];`);return `[out:json][timeout:20];(${clauses.join('')});out center 300;`;}
function categoryClauses(category){const clean=text(category).toLowerCase().trim();if(!clean)return[];const aliases={dentist:[['amenity','dentist']],dental:[['amenity','dentist']],pharmacy:[['amenity','pharmacy']],restaurant:[['amenity','restaurant']],cafe:[['amenity','cafe']],salon:[['shop','hairdresser'],['shop','beauty']],plumber:[['craft','plumber']],clinic:[['amenity','clinic'],['amenity','doctors']],hospital:[['amenity','hospital']],school:[['amenity','school']],hotel:[['tourism','hotel']]};if(aliases[clean])return aliases[clean];const value=clean.replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');return value?['amenity','shop','office','craft','tourism','leisure'].map((key)=>[key,value]):[];}
function normaliseOsmElement(element={}){const tags=element.tags||{};const lat=numberOrNull(element.lat??element.center?.lat);const lon=numberOrNull(element.lon??element.center?.lon);const type=first(tags.amenity,tags.shop,tags.office,tags.craft,tags.tourism,tags.leisure);const phone=first(tags.phone,tags['contact:phone']);const website=first(tags.website,tags['contact:website']);return{id:`osm:${element.type||'node'}:${element.id||''}`,name:text(tags.name),category:humanise(type),types:[tags.amenity,tags.shop,tags.office,tags.craft,tags.tourism,tags.leisure].filter(Boolean),rating:null,reviewCount:null,address:formatAddress(tags),phone,internationalPhone:first(tags['contact:phone'],tags.phone),website,websiteStatus:website?'not_checked':'no_website',businessStatus:'',source:'openstreetmap',sourceUrl:element.id?`https://www.openstreetmap.org/${element.type}/${element.id}`:'',latitude:lat,longitude:lon,openingHours:text(tags.opening_hours),tags:pickRelevantTags(tags)};}
function formatAddress(tags){return [tags['addr:housenumber'],tags['addr:street'],tags['addr:suburb'],tags['addr:city'],tags['addr:postcode']].filter(Boolean).join(', ');}function pickRelevantTags(tags){const keys=['amenity','shop','office','craft','tourism','leisure','cuisine','opening_hours','wheelchair','email','brand'];return Object.fromEntries(keys.filter((key)=>tags[key]).map((key)=>[key,tags[key]]));}
function matchesCategory(business,category){if(!category)return true;const needle=category.toLowerCase().replace(/[_-]/g,' ');return [business.name,business.category,...business.types].some((value)=>text(value).toLowerCase().replace(/[_-]/g,' ').includes(needle));}function withinRadius(business,center,radius){if(business.latitude===null||business.longitude===null)return false;return haversine(center.latitude,center.longitude,business.latitude,business.longitude)<=radius;}function haversine(aLat,aLon,bLat,bLon){const r=6371000;const p=Math.PI/180;const x=(bLat-aLat)*p;const y=(bLon-aLon)*p;const h=Math.sin(x/2)**2+Math.cos(aLat*p)*Math.cos(bLat*p)*Math.sin(y/2)**2;return 2*r*Math.asin(Math.sqrt(h));}
function dedupe(items){const seen=new Set();return items.filter((item)=>{const key=item.id||`${item.name}|${item.address}`;if(seen.has(key))return false;seen.add(key);return true;});}function getCache(key){const item=cache.get(key);if(!item||item.expiresAt<Date.now()){cache.delete(key);return null;}return item.value;}function setCache(key,value,ttl){cache.set(key,{value,expiresAt:Date.now()+ttl});if(cache.size>200){const oldest=cache.keys().next().value;cache.delete(oldest);}}async function waitForNominatimSlot(){const delay=Math.max(0,nextNominatimRequestAt-Date.now());nextNominatimRequestAt=Math.max(Date.now(),nextNominatimRequestAt)+1000;if(delay)await new Promise((resolve)=>setTimeout(resolve,delay));}function providerError(code,message,status){const error=new Error(message);error.code=code;error.status=status;return error;}async function fetchWithTimeout(url,options,timeoutMs){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal});}finally{clearTimeout(timer);}}function first(...values){return text(values.find((value)=>typeof value==='string'&&value.trim())||'');}function text(value){return typeof value==='string'?value:'';}function numberOrNull(value){if(value===null||value===undefined||value==='')return null;return Number.isFinite(Number(value))?Number(value):null;}function humanise(value){return text(value).replace(/_/g,' ').replace(/\b\w/g,(c)=>c.toUpperCase());}
module.exports={buildOverpassQuery,haversine,matchesCategory,normaliseOsmElement,searchOpenData,withinRadius,_cache:cache};
